
language: php

notifications:
  email:
    recipients:
    - kennethhendricks@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6

env:
  - DB=pgsql MOODLE_BRANCH=MDL-46375-master MOODLE_REPO=https://github.com/andrewnicols/moodle.git
  - DB=mysqli MOODLE_BRANCH=MDL-46375-master MOODLE_REPO=https://github.com/andrewnicols/moodle.git

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MDL-46375-master MOODLE_REPO=https://github.com/andrewnicols/moodle.git
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MDL-46375-master MOODLE_REPO=https://github.com/andrewnicols/moodle.git

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - git clone https://github.com/kenneth-hendricks/moodle-plugin-ci.git ci
  - cd ci
  - composer selfupdate
  - composer install --no-dev
  - cd ..
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
# - moodle-plugin-ci csslint    # No CSS
  - moodle-plugin-ci shifter
# - moodle-plugin-ci jshint     # No JS
  - moodle-plugin-ci phpunit
# - moodle-plugin-ci behat      # No tests yet
